### ISSUE TITLE
lpxc leaks threads

### ISSUE THREAD

**Issue by msakrejda** [ryansmith3136/lpxc#10]
https://github.com/ryandotsmith/lpxc/blob/master/lib/lpxc.rb#L95-L96

These are only cleaned up when the program exits. Perhaps add a `#close` to Lpxc?

**Comment by technomancy** [comment]
It looks like `Thread#kill` will clean up the actual connections due to the `ensure` block, so I think this should cover it?

**Comment by msakrejda** [comment]
Thanks! Is `Thread#kill` safe to do in Ruby? I know in Java `Thread.stop` was [eventually removed](http://stackoverflow.com/questions/671049/how-do-you-kill-a-thread-in-java/671052#671052) due to things like failing to handle mutex cleanup.

**Comment by technomancy** [comment]
My understanding is that there can be issues if the thread being killed shares resources with other threads; however Lpxc is pretty careful about keeping the threads isolated, so if anything fails to get cleaned up in the killed threads they should just get discarded when they're GC'd.

That said, it occurs to be that it would be better to flush before killing off the threads, so I will add that.
