### ISSUE TITLE
Lpxc.puts ignores different opts for same client

### ISSUE THREAD

**Issue by msakrejda** [ryansmith3136/lpxc#11]
This doesn't affect me but I noticed it and it may be a potential pitfall. If I call

``` ruby
Lpxc.puts("hello", "https://...", procid: 'foo')
Lpxc.puts("hello", "https://...", procid: 'bar')
```

The second call will use the `Lpxc` instance created by the first, and ignore the different `procid`. Same goes for other options.

**Comment by technomancy** [comment]
Nice catch. Does the fix in #12 look good?

**Comment by msakrejda** [comment]
Maybe? Are hashes treated by value rather than by reference when used as hash keys? Seems to check out in `irb`, but I would not have expected that to work.

**Comment by technomancy** [comment]
Yeah, Ruby's semantics around equality are highly questionable, but this does work. =)

**Comment by msakrejda** [comment]
Cool. Looks good to me, then.
